spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cookbook
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
